name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: v install

      - name: Check if code is formatted
        run: |
          v fmt -diff .
          v fmt -verify .

      - name: Run tests
        run: v test .

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: v install

      - name: Run V vet (linter)
        run: v vet .

  readme-examples:
    name: README Examples
    runs-on: ubuntu-latest
    
    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: v install

      - name: Test README examples
        run: v test readme_examples_test.v